source 'https://github.com/CocoaPods/Specs.git'

platform:ios, '9.0'
use_frameworks!

target 'WZScanQrcode_Example' do
  pod 'WZScanQrcode', :path => '../'

  target 'WZScanQrcode_Tests' do
    inherit! :search_paths

    
  end
end
